print('---------------------------------------')
print('sistema de calculo de notas')
print('---------------------------------------')
n1 = float (input('digite a primeira nota: '))
n2 = float (input('digite a segunda nota: '))
print('de acordo com a primeira nota informada ({}) e a segunda nota ({}), temos a seguinte media {}' .format(n1,n2, (n1+n2)/2),end='<<<<<')