n1 = float (input('Digite o primeiro numero :'))
n2 = float (input('Digite o segundo numero: '))
print('a soma dos numeros é {}'.format(n1+n2))
print('a subtração dos numeros é {}'.format(n1-n2))
print('a multiplicação dos numeros é {}'.format(n1 * n2))
print ('a divisão dos numeros é {}'.format(n1/n2))
print('a exponenciação dos numeros é {}'.format(n1**n2))
print ('a divisão inteira, ou seja, apenas a primeira parte é {}'.format(n1//n2))
print ('o resto da divisão de {} e {} é {}'.format(n1,n2, n1 % n2))